import AppKit
import ApplicationServices

/// Reads the current selection and inserts text into the frontmost app.
///
/// Insertion goes through the pasteboard + a synthetic `⌘V`, which works in every app
/// (including terminals and Electron apps). The user's clipboard is restored afterwards.
@MainActor
enum TextInserter {
    /// Pasteboard types that tell clipboard managers to ignore our temporary content.
    private static let transientTypes = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    static func insert(_ text: String, restoreClipboard: Bool) async {
        let pasteboard = NSPasteboard.general
        let saved = restoreClipboard ? PasteboardSnapshot(pasteboard) : nil

        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        for type in transientTypes { pasteboard.setData(Data(), forType: type) }

        postShortcut(key: KeyCode.v)

        if let saved {
            // Give the target app time to read the pasteboard before putting the old content back.
            try? await Task.sleep(for: .milliseconds(450))
            saved.restore(to: pasteboard)
        }
    }

    /// Selected text in the focused app: Accessibility API first, then a synthetic `⌘C`.
    static func selectedText() async -> String? {
        if let text = accessibilitySelection(), !text.isEmpty { return text }
        return await copySelection()
    }

    private static func accessibilitySelection() -> String? {
        let system = AXUIElementCreateSystemWide()
        var focused: CFTypeRef?
        guard AXUIElementCopyAttributeValue(system, kAXFocusedUIElementAttribute as CFString, &focused) == .success,
              let focused, CFGetTypeID(focused) == AXUIElementGetTypeID() else { return nil }
        var selection: CFTypeRef?
        guard AXUIElementCopyAttributeValue(focused as! AXUIElement, kAXSelectedTextAttribute as CFString, &selection) == .success
        else { return nil }
        return selection as? String
    }

    private static func copySelection() async -> String? {
        let pasteboard = NSPasteboard.general
        let saved = PasteboardSnapshot(pasteboard)
        let before = pasteboard.changeCount

        postShortcut(key: KeyCode.c)

        var copied: String?
        for _ in 0..<25 {
            try? await Task.sleep(for: .milliseconds(20))
            if pasteboard.changeCount != before {
                copied = pasteboard.string(forType: .string)
                break
            }
        }
        saved.restore(to: pasteboard)
        return copied
    }

    private static func postShortcut(key: CGKeyCode) {
        let source = CGEventSource(stateID: .combinedSessionState)
        for isDown in [true, false] {
            let event = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: isDown)
            // Explicit flags so physical keys the user may still hold (fn, ⌥) don't leak in.
            event?.flags = .maskCommand
            event?.post(tap: .cghidEventTap)
        }
    }

    private enum KeyCode {
        static let c: CGKeyCode = 8
        static let v: CGKeyCode = 9
    }
}

/// A copy of every item and type on a pasteboard, so it can be put back later.
@MainActor
private struct PasteboardSnapshot {
    private let items: [[NSPasteboard.PasteboardType: Data]]

    init(_ pasteboard: NSPasteboard) {
        items = (pasteboard.pasteboardItems ?? []).map { item in
            var types: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) { types[type] = data }
            }
            return types
        }
    }

    func restore(to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        guard !items.isEmpty else { return }
        let restored = items.map { types in
            let item = NSPasteboardItem()
            for (type, data) in types { item.setData(data, forType: type) }
            return item
        }
        pasteboard.writeObjects(restored)
    }
}
